# Generated by Django 3.2.5 on 2021-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_habit_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='complete',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.AddField(
            model_name='habit',
            name='Fri',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Mon',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Sat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Sun',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Thu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Tue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='Wed',
            field=models.TextField(null=True),
        ),
    ]
