# Generated by Django 3.2.5 on 2021-12-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211208_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='done',
            new_name='complete',
        ),
    ]
