# Generated by Django 3.2.5 on 2021-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_done_habit_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='name',
            new_name='title',
        ),
    ]
